/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        bg: "var(--bg)",
        "bg-elev-1": "var(--bg-elev-1)",
        "bg-elev-2": "var(--bg-elev-2)",
        panel: "var(--panel)",
        card: "var(--card)",
        "card-2": "var(--card-2)",
        border: "var(--border)",
        "border-2": "var(--border-2)",
        divider: "var(--divider)",
        text: "var(--text)",
        "text-2": "var(--text-2)",
        "text-3": "var(--text-3)",
        "text-invert": "var(--text-invert)",
        brand: "var(--brand)",
        "brand-2": "var(--brand-2)",
        blue: "var(--blue)",
        green: "var(--green)",
        red: "var(--red)",
        amber: "var(--amber)",
        cyan: "var(--cyan)",
        focus: "var(--focus)",
        hover: "var(--hover)",
        active: "var(--active)",
        selected: "var(--selected)",
        "update-glow": "var(--update-glow)",
      },
      borderRadius: {
        xs: "var(--r-xs)",
        sm: "var(--r-sm)",
        md: "var(--r-md)",
        lg: "var(--r-lg)",
      },
      boxShadow: {
        1: "var(--shadow-1)",
        2: "var(--shadow-2)",
      },
      spacing: {
        "top-toolbar": "var(--top-toolbar-height)",
        "status-bar": "var(--status-bar-height)",
        "activity-bar": "var(--activity-bar-width)",
        sidebar: "var(--sidebar-width)",
        inspector: "var(--inspector-width)",
      },
    },
  },
  plugins: [],
}
