export const TEST_NARRATIVE_IDE_INVOKE_METHODS = {
  pickDirectory: 'dialog:pick-directory',
  loadAppSettings: 'settings:load-app',
  saveAppSettings: 'settings:save-app',
  pickFiles: 'dialog:pick-files',
  testProviderConnection: 'settings:test-provider',
  aiChat: 'ai:chat',
  aiGenerateImage: 'ai:generate-image',
  portraitSave: 'portrait:save',
  portraitUpload: 'portrait:upload',
  dbOpen: 'db:open',
  dbClose: 'db:close',
  dbUpsert: 'db:upsert',
  dbGetAll: 'db:getAll',
  dbDelete: 'db:delete',
  dbSearch: 'db:search',
  w3Start: 'w3:start',
  w3Select: 'w3:select',
  w3Status: 'w3:status',
  w1Start: 'w1:start',
  w1Cancel: 'w1:cancel',
  w1Status: 'w1:status',
  w1Console: 'w1:console',
  w1SetBreakpoint: 'w1:set_breakpoint',
  w1Resume: 'w1:resume',
  w1Rewind: 'w1:rewind',
  fetchPrompts: 'prompts:list',
  sidecarSpawn: 'sidecar:spawn',
  w2Start: 'w2:start',
  w2Status: 'w2:status',
  w4Start: 'w4:start',
  w4Status: 'w4:status',
  w5Start: 'w5:start',
  w5Status: 'w5:status',
  w6Start: 'w6:start',
  w6Status: 'w6:status',
  metadataIngest: 'metadata:ingest',
  metadataStatus: 'metadata:status',
  orchestratorStart: 'orchestrator:start',
  orchestratorStatus: 'orchestrator:status',
  orchestratorGrant: 'orchestrator:grant',
  orchestratorDeny: 'orchestrator:deny',
} as const;

export type TestBridgeMethodMap = typeof TEST_NARRATIVE_IDE_INVOKE_METHODS;
